// SPDX-FileCopyrightText: 2026 Muninn contributors
// SPDX-License-Identifier: AGPL-3.0-only

export const DEFAULT_WEBVIEW_STRINGS = {
  taskCheckboxLabel: 'Toggle task',
  commandLabelTask: 'Task',
  commandLabelStrike: 'Strikethrough',
  commandLabelHeadings: 'Headings',
  commandLabelFileLink: 'File link',
  statusSyncConflict:
    'The document changed elsewhere. Preserving your edits in a recovery document.',
  statusSyncPending: 'Edits are still synchronizing. Retry once synchronization finishes.',
  statusSourceRequired:
    'This edit cannot preserve the original Markdown. Use Source to make this change safely.',
  toolbarAriaLabel: 'Muninn markdown toolbar',
  toolbarGroupTextLabel: 'Text',
  toolbarGroupStructureLabel: 'Structure',
  toolbarGroupInsertLabel: 'Insert',
  toolbarButtonBoldTitle: 'Bold (Ctrl/Cmd+B)',
  toolbarButtonItalicTitle: 'Italic (Ctrl/Cmd+I)',
  toolbarButtonLinkTitle: 'Insert or remove link',
  toolbarButtonBulletTitle: 'Toggle bullet list',
  toolbarButtonNumberedTitle: 'Toggle numbered list',
  toolbarButtonBulletLabel: 'Bullet',
  toolbarButtonNumberedLabel: 'Numbered',
  toolbarButtonTableTitle: 'Insert table (Ctrl/Cmd+Alt+T)',
  toolbarButtonCodeTitle: 'Insert code block',
  toolbarButtonMermaidTitle: 'Insert Mermaid diagram (Ctrl/Cmd+Alt+M)',
  toolbarButtonSourceTitle: 'Open raw Markdown source in VS Code',
  toolbarButtonMermaidLabel: 'Mermaid',
  toolbarButtonSourceLabel: 'Source',
  toolbarBlockStyleLabel: 'Block style',
  toolbarBlockStyleCurrentTemplate: 'Block style: {0}',
  toolbarGroupUtilitiesLabel: 'Document',
  pickerStaleMessage:
    'The document changed while the picker was open. Select the block again and retry.',
  tableAddButton: 'Add to table',
  toolbarMoreLabel: 'More',
  toolbarMoreTitle: 'Show advanced toolbar actions',
  editorAriaLabel: 'Markdown editor',
  editorAriaLabelTemplate: 'Markdown editor — {0}',
  statusReady: 'Ready',
  statusErrorTemplate: 'Error: {0}',
  commandLabelBold: 'Bold',
  commandLabelItalic: 'Italic',
  commandLabelHeading1: 'Heading 1',
  commandLabelHeading2: 'Heading 2',
  commandLabelHeading3: 'Heading 3',
  commandLabelParagraph: 'Paragraph',
  commandLabelBulletList: 'Bullet list',
  commandLabelNumberedList: 'Numbered list',
  commandLabelLink: 'Link',
  commandLabelMermaidDiagram: 'Mermaid diagram',
  commandLabelTable: 'Table',
  commandLabelCodeBlock: 'Code block',
  commandLabelAddTableRow: 'Add table row',
  commandLabelAddTableColumn: 'Add table column',
  commandLabelSourceEditor: 'Source editor',
  commandFailureAddRowNoTable: 'Insert a table first before adding a row.',
  commandFailureAddColumnNoTable: 'Insert a table first before adding a column.',
  commandFailureGenericTemplate:
    'Could not run {0}. Place the cursor in editable text and try again.',
  statusInsertedMermaid: 'Inserted Mermaid block.',
  statusInsertedTable: 'Inserted table.',
  statusInsertedCodeBlock: 'Inserted code block. Set language from block header.',
  statusImageAddedTemplate: 'Image added: {0}',
  statusInsertImageFailed: 'Could not read image. Please retry.',
  statusAwaitingLinkInput: 'Awaiting link input…',
  statusInsertedLink: 'Inserted link.',
  statusRemovedLink: 'Removed link.',
  statusConnected: 'Connected',
  statusInsertLinkFailed: 'Failed to insert link.',
  codeBlockTitle: 'Code',
  codeBlockLanguageAriaLabel: 'Code block language',
  codeBlockLanguageUnsupportedTemplate: 'Unsupported ({0})',
  statusCodeLanguageUpdateFailed: 'Could not update code block language. Please retry.',
  statusCodeLanguagePlainText: 'Code block language set to plain text.',
  statusCodeLanguageSetTemplate: 'Code block language set to {0}.',
  frontMatterLabel: 'Front matter',
  frontMatterAriaLabel: 'Front matter metadata block',
  tableTitle: 'Table',
  tableDeleteAriaLabel: 'Delete table',
  tableViewSourceButton: 'View Source',
  tableSourceAriaLabel: 'Markdown table source',
  tableApplySourceButton: 'Apply Source',
  tableApplySourceTitle: 'Apply source (Ctrl/Cmd+Enter)',
  tableSourceHint: 'Edit Markdown table source. Press Ctrl/Cmd+Enter to apply changes.',
  tableGridAriaLabelTemplate: 'Table {0}: {1} columns, {2} rows',
  tableHeaderColumnLabelTemplate: 'Header column {0}',
  tableNewColumnHeaderTemplate: 'Column {0}',
  tableRowColumnLabelTemplate: 'Row {0} column {1}',
  statusTableUpdated: 'Table updated.',
  statusTableDeleteFailed: 'Could not delete table. Please retry.',
  statusTableDeleted: 'Deleted table.',
  tableBackToPreviewButton: 'Back to Preview',
  tableSourceFeedbackAppliedTemplate: 'Applied: {0}',
  statusTableSourceApplied: 'Table source applied.',
  statusTableSourceApplyFailed:
    'Could not apply this table edit. Your draft is retained. Reopen the table or use Source to apply it safely.',
  statusTableSourceInvalid:
    'Use a Markdown header row followed by a separator row, such as | --- |.',
  mermaidDisabledMessage:
    'Mermaid preview is disabled for this workspace. Enable muninn.integrations.mermaid.enabled and trust the workspace, or allow Mermaid in restricted workspaces.',
  mermaidNoSvgOutput: 'Mermaid rendered no SVG output.',
  mermaidDiagramAriaLabel: 'Mermaid diagram',
  mermaidDiagramAriaLabelTemplate: 'Mermaid diagram: {0}',
};

export type WebviewStrings = typeof DEFAULT_WEBVIEW_STRINGS;
